#pragma once

#include "TestScript.h"
#include "TestScript2.h"
#include "RotateAround.h"
#include "PlayerController.h"
#include "PlayerCameraFollower.h"
#include "GhostController.h"
#include "PlayerUpgrader.h"
#include "MiniGhost.h"
#include "EnemyController.h"
#include "BossController.h"
#include "MapCellOptimizer.h"
#include "CellSupervisor.h"
#include "GateOpener.h"
#include "StatueUser.h"
#include "TriggerTest.h"
#include "GUIStatistics.h"
#include "TutorialPlayground.h"
#include "TutorialEnemy.h"
#include "MudController.h"
#include "FireController.h"
#include "GasController.h"
#include "Credits.h"

#include "Bosses/Necromancer.h"

#include "Upgrades/GhostDistance.h"
#include "Upgrades/GhostRecovery.h"
#include "Upgrades/GhostSpeed.h"
#include "Upgrades/GhostActiveLines.h"
#include "Upgrades/PushbackDistance.h"
#include "Upgrades/PushbackForce.h"